import Head from 'next/head';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import About from '@/components/About';

export default function Home() {
  return (
    <div
      className={
        'bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'
      }
    >
      <Head>
        <title>UX Designer Leander Lindahl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* Header */}
      <section id={'hero'} className={'snap-start'}>
        <Hero />
      </section>
      {/* Hero */}
      <section id="about" className={'snap-center'}>
        <About />
      </section>
      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact me */}
    </div>
  );
}
